- name: Backup data
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Create backup folder
      ansible.builtin.file:
        path: "{{ playbook_dir }}/backup/"
        state: directory

    - name: Backup WLAN-keys
      become: true
      ansible.posix.synchronize:
        src: /etc/NetworkManager/system-connections/
        dest: "{{ playbook_dir }}/backup/wlan"
        archive: true
        delete: true

    - name: Backup SSH keys and config
      ansible.posix.synchronize:
        src: ~/.ssh/
        dest: "{{ playbook_dir }}/backup/ssh/"
        archive: true
        delete: true

    - name: Backup repos
      become: true
      ansible.posix.synchronize:
        src: ~/repos/
        dest: "{{ playbook_dir }}/backup/repos/"
        archive: true
        owner:
        delete: true
        rsync_opts: ["--exclude=*{{ playbook_dir }}/backup*"]

    - name: Compress backup into backup.tgz
      become: true
      community.general.archive:
        path: "{{ playbook_dir }}/backup/"
        dest: "{{ playbook_dir }}/backup.tgz"
