- name: Configure APT
  tags: [never, packages_configure]
  include_tasks: 
    file: apt.yml
    apply:
      tags: packages_configure

- name: Install base packages
  tags: [never, packages_install]
  include_tasks:
    file: packages.yml
    apply:
      tags: packages_install

- name: Install 3dparty packages
  tags: [never, packages_3dparty]
  include_tasks:
    file: 3dparty.yml
    apply:
      tags: packages_3dparty 

- name: Install tap
  tags: [never, packages_tap]
  include_tasks:
    file: tap.yml
    apply:
      tags: packages_tap 

- name: Install PPA packages
  tags: [never, packages_ppa]
  include_tasks:
    file: ppa.yml
    apply:
      tags: packages_ppa
