- name: Upgrade system
  become: true
  ansible.builtin.apt:
    update_cache: yes
    upgrade: dist
    autoremove: yes

- name: Install base packages
  become: true
  ansible.builtin.apt:
    pkg: "{{ base_packages }}"
    state: present

- name: Install base packages (sid)
  become: true
  tags: never
  ansible.builtin.apt:
    pkg: "{{ sid_packages }}"
    default_release: sid
    state: present