- name: Upgrade system
  become: true
  ansible.builtin.apt:
    update_cache: yes
    upgrade: dist
    autoremove: yes

- name: Install base packages
  become: true
  ansible.builtin.apt:
    pkg: "{{ base_packages }}"
    state: present