- name: Backup sources.list
  become: true
  ansible.builtin.command:
    cmd: mv /etc/apt/sources.list /etc/apt/sources.list.bak
    removes: /etc/apt/sources.list

- name: Copy sid.list
  become: true
  ansible.builtin.copy:
    src: sid.list
    dest: /etc/apt/sources.list.d/

- name: Upgrade system
  become: true
  ansible.builtin.apt:
    update_cache: yes
    upgrade: dist
    autoremove: yes

