base_packages:
  # Desktop environment
  - lightdm
  - i3
  - light-locker
  - polybar
  - plymouth
  - rofi
  - redshift
  - light
  - network-manager-gnome

  # File Manager
#  - ranger

  # Virtualization
  - virt-manager
  - qemu
  - ovmf
  - bridge-utils

  # Audio
  - pulseaudio
#  - pamixer
  - pavucontrol

  # Office
  - libreoffice
  - texlive
  - thunderbird
 # - lightning

  # Programming
  - build-essential
  - git
  - rustc
  - cargo
  - octave
  - wireshark
  - golang
  - nmap

  # System Utils
  - network-manager
  - firewalld
  - fail2ban
  - software-properties-common
  - arandr

  # Bluetooth
  - blueman
  - pulseaudio-module-bluetooth
  
  # Terminal & Shell
  - fish
  - tmux

  # Browser
  - firefox
  - chromium

  # Utils
  - telegram-desktop
  - nextcloud-desktop
  - nextcloud-desktop-cmd
  - keepassxc
  - vlc
  - filezilla
  - vim
  - feh
  - speedcrunch
  - cups
  - ranger
  - ncdu
  - lshw
  - flameshot
  - htop
  - rsync
  - curl
  - hcloud-cli


mpr_packages:
  - code-bin

  # Terminal
  - alacritty


third_party:
  - {package: code, key: https://packages.microsoft.com/keys/microsoft.asc, repo: "deb [signed-by=/usr/share/keyrings/code.gpg arch=amd64,arm64,armhf] https://packages.microsoft.com/repos/code stable main"}
  - {package: teams, key: https://packages.microsoft.com/keys/microsoft.asc, repo: "deb [signed-by=/usr/share/keyrings/teams.gpg arch=amd64] https://packages.microsoft.com/repos/ms-teams stable main"}
  - {package: makedeb, key: https://proget.hunterwittenborn.com/debian-feeds/makedeb.pub, repo: "deb [signed-by=/usr/share/keyrings/makedeb.gpg arch=all] https://proget.hunterwittenborn.com/ makedeb main"}
  - {package: element-desktop, key: https://packages.riot.im/debian/element-io-archive-keyring.asc, repo: "deb [signed-by=/usr/share/keyrings/element-desktop.gpg] https://packages.riot.im/debian/ default main"}
  - {package: kubectl, key: https://packages.cloud.google.com/apt/doc/apt-key.gpg, repo: "deb [signed-by=/usr/share/keyrings/kubectl.gpg] https://apt.kubernetes.io/ kubernetes-xenial main"}
  - {package: terraform, key: https://apt.releases.hashicorp.com/gpg, repo: "deb [signed-by=/usr/share/keyrings/terraform.gpg arch=amd64] https://apt.releases.hashicorp.com buster main"}
  - {package: spotify-client, key: https://download.spotify.com/debian/pubkey_0D811D58.gpg, repo: "deb [signed-by=/usr/share/keyrings/spotify-client.gpg] http://repository.spotify.com stable non-free"}



  


ppa_repositories:
  - ppa:mmstick76/alacritty

ppa_packages:
  -  alacritty
