- name: Install regolith packages
  become: true
  ansible.builtin.apt:
    pkg: "{{ regolith_packages }}"
    state: present

- name: Remove unused regolith packages
  become: true
  ansible.builtin.apt:
    pkg: "{{ regolith_packages_remove }}"
    state: absent