- block:
  - name: Search for custom aliases
    find:
      paths: "{{ playbook_dir }}/dotfiles/oh-my-bash/custom/aliases"
      file_type: file
    register: find

  - name: Link custom aliases
    ansible.builtin.file:
      src: "{{ item.path }}"
      dest: "~/.config/oh-my-bash/custom/aliases/{{ item.path | basename }}"
      state: link
    with_items: "{{ find.files }}"

  - name: Search for custom plugins
    find:
      paths: "{{ playbook_dir }}/dotfiles/oh-my-bash/custom/plugins"
      file_type: directory
    register: find

  - name: Link custom plugins
    ansible.builtin.file:
      src: "{{ item.path }}"
      dest: "~/.config/oh-my-bash/custom/plugins/{{ item.path | basename }}"
      state: link
    with_items: "{{ find.files }}"

  - name: Search for custom themes
    find:
      paths: "{{ playbook_dir }}/dotfiles/oh-my-bash/custom/themes"
      file_type: directory
    register: find

  - name: Link custom themes
    ansible.builtin.file:
      src: "{{ item.path }}"
      dest: "~/.config/oh-my-bash/custom/themes/{{ item.path | basename }}"
      state: link
    with_items: "{{ find.files }}"

- block:
  - name: remove bashrc
    ansible.builtin.file:
      state: absent
      dest: ~/.bashrc

  - name: Link bashrc
    ansible.builtin.file:
      src: "{{ playbook_dir }}/dotfiles/oh-my-bash/bashrc"
      dest: ~/.bashrc
      state: link