- name: Get tap repository
  ansible.builtin.git:
    repo: https://mpr.hunterwittenborn.com/tap.git
    dest: ~/repos/extern/tap

- name: Build and install tap using makedeb
  ansible.builtin.command:
    cmd: makedeb -si --no-confirm
    chdir: ~/repos/extern/tap


- name: Update tap cache
  become: true
  ansible.builtin.command: tap update

- name: Install MPR packages
  become: true
  ansible.builtin.command:
    argv:
      - tap
      - install
      - "{{ item }}"
  with_items: "{{ mpr_packages }}"